### ISSUE TITLE
Einbau Social Media: Facebook

### ISSUE THREAD

**Issue by nirbos** [nirbos/TAWL#20]
Einbau des Facebook "Like"-Buttons zu jedem Beitrag sowie generell innerhalb der Hauptnavigation.
Vermutlich ist nahe der Headline der beste Ort.

Siehe: #22

**Comment by bikrambhattacharya** [comment]
@nirbos In which file I have to change the button position?

**Comment by nirbos** [comment]
@bikrambhattacharya Thank you for your interest! The social media-buttons are not implemented yet. They will be implemented in /dev/blocks/article/article.twig and /article.hogan. 
Within the next week or so we try to push a tawl JS class wich then is supposed handle the whole social media functionality. So i think its best to wait.
