### ISSUE TITLE
Anonymisierung der Server-Logs

### ISSUE THREAD

**Issue by nirbos** [nirbos/TAWL#23]
Meines Erachtens sollten wir unser Möglichstes tun, damit wir niemals personenbezogene Daten eines Besuchers speichern.
Abgesehen von den Daten: "Welcher Browser wurde verwendet", und, "Welche Seite/Beitrag wurde aufgerufen", (meines Erachtens keine persönlichen Daten) sollten wir unser Möglichstes tun um alles sofort zu löschen oder gar nicht erst zu speichern. In jedem Fall zum Beispiel die IP-Adresse.

Diesen Umstand sollten wir dann auch in die Statics aufnehmen.

**Comment by m-pire** [comment]
Habe dazu ein kleines Skript geschrieben, dass eben dieses live macht, ohne die IP Adressen überhaupt vorher im Klartext zu schreiben. Ich werde das beobachten und sehen ob es performance-Einbrüche mit sich bringt.

**Comment by m-pire** [comment]
Nach einem kleinen Benchmark sieht das richtig gut aus, das kann so weiterlaufen.
