### ISSUE TITLE
zerhackte Worte und Zahlen - Zeilenumbrüche

### ISSUE THREAD

**Issue by mychecknix** [nirbos/TAWL#32]
Zei
t
am Dartum des 1
9.10.2017 B
eispiel

Dieses Bild ist sehr häufig und störend in den Quellenangaben zu sehen.

**Comment by mychecknix** [comment]
Vorschlag die Drei Blöcke <Link-Quelle>, <Datum> und <Lizenz> mit einem festen Zeilenumbruch versehen, da meistens genügend Platz nach unten ist.

Beispiel:

  9. [lorem ipsum](http://www.loremipsum.de/)
      18. Sep. 2017
      [Zitat](https://www.gesetze-im-internet.de/urhg/__51.html)
10. [lorem ipsum](http://www.loremipsum.de/)
      18. Sep. 2017
      [Zitat](https://www.gesetze-im-internet.de/urhg/__51.html)

**Comment by nirbos** [comment]
Vielen Dank für Ihr Feedback. Sie haben vollkommen Recht, die Quellenangaben benötigen eine Überarbeitung.
